<?php
// journey.phtml
$form->get('journey')->setName('o:block[__blockIndex__][o:data][journey]');
$form->get('journey')->get('property')->setValue($data['journey']['property'] ?? '');
$form->prepare();
?>
<a href="#" class="collapse">
    <h4><?= $this->translate('Journey'); ?></h4>
</a>
<div class="collapsible">
    <p>Geo shapes that are not markers will be excluded from the journey.</p>
    <?= $this->formCollection($form->get('journey'), false); ?>
</div>